# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_passw'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companyWeight',
            field=models.IntegerField(default=5),
        ),
    ]
