# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_companyweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userInvestment',
        ),
    ]
