# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_userinvestment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='investmentRentability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rentability',
        ),
    ]
