# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:09
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=accounts.models.UploadToPathAndRename('avatars'))),
                ('position', models.CharField(max_length=20)),
                ('investment', models.IntegerField()),
                ('area', models.FloatField()),
                ('company', models.CharField(max_length=20)),
                ('holding', models.CharField(max_length=20)),
                ('cluster', models.CharField(max_length=5)),
                ('total', models.IntegerField()),
                ('ebitda', models.IntegerField()),
                ('userInvestment', models.IntegerField()),
                ('teamInvestment', models.IntegerField()),
                ('teamInvestment1', models.IntegerField()),
                ('teamInvestment2', models.IntegerField()),
                ('rentability', models.FloatField()),
                ('investmentRentability', models.FloatField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
