# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170316_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passw',
            field=models.CharField(default='', max_length=20),
        ),
    ]
